# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(680, 300)
        Dialog.setStyleSheet("font: 75 10pt \"Comfortaa\";\n"
"background: #3a3a3a;")
        self.label_link = QtWidgets.QLabel(Dialog)
        self.label_link.setGeometry(QtCore.QRect(20, 20, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_link.setFont(font)
        self.label_link.setStyleSheet("color: #fff;")
        self.label_link.setObjectName("label_link")
        self.label_Age = QtWidgets.QLabel(Dialog)
        self.label_Age.setGeometry(QtCore.QRect(20, 70, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_Age.setFont(font)
        self.label_Age.setStyleSheet("color: #fff;")
        self.label_Age.setObjectName("label_Age")
        self.label_Year = QtWidgets.QLabel(Dialog)
        self.label_Year.setGeometry(QtCore.QRect(280, 70, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_Year.setFont(font)
        self.label_Year.setStyleSheet("color: #fff;")
        self.label_Year.setObjectName("label_Year")
        self.label_time = QtWidgets.QLabel(Dialog)
        self.label_time.setGeometry(QtCore.QRect(460, 70, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("color: #fff;")
        self.label_time.setObjectName("label_time")
        self.lineEdit_link = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_link.setGeometry(QtCore.QRect(170, 10, 501, 41))
        self.lineEdit_link.setStyleSheet("background: #fff;\n"
"color: #000;\n"
"padding: 10px;\n"
"border-radius: 20px;")
        self.lineEdit_link.setText("")
        self.lineEdit_link.setPlaceholderText("")
        self.lineEdit_link.setObjectName("lineEdit_link")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(20, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(False)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background: #a016f0;\n"
"color: #fff;\n"
"border-radius: 10px;")
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoDefault(True)
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_Age = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Age.setGeometry(QtCore.QRect(30, 120, 171, 41))
        self.lineEdit_Age.setStyleSheet("background: #fff;\n"
"color: #000;\n"
"padding: 10px;\n"
"border-radius: 20px;")
        self.lineEdit_Age.setText("")
        self.lineEdit_Age.setObjectName("lineEdit_Age")
        self.lineEdit_Year = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Year.setGeometry(QtCore.QRect(280, 120, 101, 41))
        self.lineEdit_Year.setStyleSheet("background: #fff;\n"
"color: #000;\n"
"padding: 10px;\n"
"border-radius: 20px;")
        self.lineEdit_Year.setText("")
        self.lineEdit_Year.setObjectName("lineEdit_Year")
        self.lineEdit_time = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_time.setGeometry(QtCore.QRect(460, 120, 171, 41))
        self.lineEdit_time.setStyleSheet("background: #fff;\n"
"color: #000;\n"
"padding: 10px;\n"
"border-radius: 20px;")
        self.lineEdit_time.setText("")
        self.lineEdit_time.setObjectName("lineEdit_time")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_link.setText(_translate("Dialog", "Ссылка на сайт"))
        self.label_Age.setText(_translate("Dialog", "Возрастное ограничение"))
        self.label_Year.setText(_translate("Dialog", "Год выхода"))
        self.label_time.setText(_translate("Dialog", "Длительность фильма"))
        self.pushButton.setText(_translate("Dialog", "Отправить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
