# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(680, 300)
        Dialog.setMinimumSize(QtCore.QSize(680, 300))
        Dialog.setMaximumSize(QtCore.QSize(680, 300))
        Dialog.setWindowTitle("Kuнoмaнuя NEWS")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("font: 75 10pt \"Comfortaa\";\n"
"background: #3a3a3a;")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(20, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(False)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background: #a016f0;\n"
"color: #fff;\n"
"border-radius: 10px;")
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoDefault(True)
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.toolButton = QtWidgets.QToolButton(Dialog)
        self.toolButton.setGeometry(QtCore.QRect(570, 240, 91, 41))
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton.setStyleSheet("background: #a016f0;\n"
"color: #fff;\n"
"border-radius: 10px;")
        self.toolButton.setObjectName("toolButton")
        self.treeWidget = QtWidgets.QTreeWidget(Dialog)
        self.treeWidget.setGeometry(QtCore.QRect(300, 170, 161, 101))
        self.treeWidget.setStyleSheet("background-color: #a016f0;")
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 60, 651, 101))
        self.widget.setObjectName("widget")
        self.other_Input = QtWidgets.QGridLayout(self.widget)
        self.other_Input.setContentsMargins(0, 0, 0, 0)
        self.other_Input.setObjectName("other_Input")
        self.label_Age = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_Age.setFont(font)
        self.label_Age.setStyleSheet("color: #fff;")
        self.label_Age.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Age.setObjectName("label_Age")
        self.other_Input.addWidget(self.label_Age, 1, 2, 1, 1)
        self.label_smile = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_smile.setFont(font)
        self.label_smile.setStyleSheet("color: #fff;")
        self.label_smile.setAlignment(QtCore.Qt.AlignCenter)
        self.label_smile.setObjectName("label_smile")
        self.other_Input.addWidget(self.label_smile, 1, 6, 1, 1)
        self.label_color = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_color.setFont(font)
        self.label_color.setStyleSheet("color: #fff;")
        self.label_color.setAlignment(QtCore.Qt.AlignCenter)
        self.label_color.setObjectName("label_color")
        self.other_Input.addWidget(self.label_color, 1, 5, 1, 1)
        self.lineEdit_time = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_time.setStyleSheet("background: #fff;\n"
"color: #000;\n"
"padding: 10px;\n"
"border-radius: 20px;")
        self.lineEdit_time.setText("")
        self.lineEdit_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.other_Input.addWidget(self.lineEdit_time, 2, 4, 1, 1)
        self.lineEdit_Year = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Year.setStyleSheet("background: #fff;\n"
"color: #000;\n"
"padding: 10px;\n"
"border-radius: 20px;")
        self.lineEdit_Year.setText("")
        self.lineEdit_Year.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Year.setObjectName("lineEdit_Year")
        self.other_Input.addWidget(self.lineEdit_Year, 2, 0, 1, 1)
        self.label_time = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("color: #fff;")
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.other_Input.addWidget(self.label_time, 1, 4, 1, 1)
        self.label_smile_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_smile_2.setFont(font)
        self.label_smile_2.setStyleSheet("color: #fff;")
        self.label_smile_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_smile_2.setObjectName("label_smile_2")
        self.other_Input.addWidget(self.label_smile_2, 1, 7, 1, 1)
        self.label_Year = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_Year.setFont(font)
        self.label_Year.setStyleSheet("color: #fff;")
        self.label_Year.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Year.setObjectName("label_Year")
        self.other_Input.addWidget(self.label_Year, 1, 0, 1, 1)
        self.lineEdit_color = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_color.setStyleSheet("background: #fff;\n"
"color: #000;\n"
"padding: 10px;\n"
"border-radius: 20px;")
        self.lineEdit_color.setText("")
        self.lineEdit_color.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_color.setObjectName("lineEdit_color")
        self.other_Input.addWidget(self.lineEdit_color, 2, 5, 1, 1)
        self.lineEdit_Age = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_Age.setStyleSheet("background: #fff;\n"
"color: #000;\n"
"padding: 10px;\n"
"border-radius: 20px;")
        self.lineEdit_Age.setText("")
        self.lineEdit_Age.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Age.setObjectName("lineEdit_Age")
        self.other_Input.addWidget(self.lineEdit_Age, 2, 2, 1, 1)
        self.lineEdit_smile2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_smile2.setStyleSheet("background: #fff;\n"
"color: #000;\n"
"padding: 10px;\n"
"border-radius: 20px;")
        self.lineEdit_smile2.setText("")
        self.lineEdit_smile2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_smile2.setObjectName("lineEdit_smile2")
        self.other_Input.addWidget(self.lineEdit_smile2, 2, 7, 1, 1)
        self.lineEdit_smile1 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_smile1.setStyleSheet("background: #fff;\n"
"color: #000;\n"
"padding: 10px;\n"
"border-radius: 20px;")
        self.lineEdit_smile1.setText("")
        self.lineEdit_smile1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_smile1.setObjectName("lineEdit_smile1")
        self.other_Input.addWidget(self.lineEdit_smile1, 2, 6, 1, 1)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 651, 45))
        self.widget1.setObjectName("widget1")
        self.main_Link = QtWidgets.QGridLayout(self.widget1)
        self.main_Link.setContentsMargins(0, 0, 0, 0)
        self.main_Link.setObjectName("main_Link")
        self.label_link = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_link.setFont(font)
        self.label_link.setStyleSheet("color: #fff;\n"
"margin-right: 20px;")
        self.label_link.setAlignment(QtCore.Qt.AlignCenter)
        self.label_link.setObjectName("label_link")
        self.main_Link.addWidget(self.label_link, 0, 0, 1, 1)
        self.lineEdit_link = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_link.setStyleSheet("background: #fff;\n"
"color: #000;\n"
"padding: 10px;\n"
"border-radius: 20px;")
        self.lineEdit_link.setText("")
        self.lineEdit_link.setObjectName("lineEdit_link")
        self.main_Link.addWidget(self.lineEdit_link, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton.setText(_translate("Dialog", "Отправить"))
        self.toolButton.setText(_translate("Dialog", "Settings"))
        self.treeWidget.headerItem().setText(0, _translate("Dialog", "Хоррор"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Dialog", ":scream:"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Dialog", ":jack_o_lantern:"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label_Age.setText(_translate("Dialog", "Возраст"))
        self.label_smile.setText(_translate("Dialog", "Смайл-1"))
        self.label_color.setText(_translate("Dialog", "Цвет"))
        self.lineEdit_time.setPlaceholderText(_translate("Dialog", "110"))
        self.lineEdit_Year.setPlaceholderText(_translate("Dialog", "2012"))
        self.label_time.setText(_translate("Dialog", "Длительность"))
        self.label_smile_2.setText(_translate("Dialog", "Смайл-2"))
        self.label_Year.setText(_translate("Dialog", "Год выхода"))
        self.lineEdit_Age.setPlaceholderText(_translate("Dialog", "18"))
        self.label_link.setWhatsThis(_translate("Dialog", "<html><head/><body><p>Здесь должна быть ссылка на сайт.</p><p>Рекомендованный сайт - HDREZKA</p></body></html>"))
        self.label_link.setText(_translate("Dialog", "Ссылка на сайт"))
        self.lineEdit_link.setPlaceholderText(_translate("Dialog", "http://101kinopoisk.com/films/horror/549-sinister-2012.html"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
