# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(661, 378)
        Settings.setMinimumSize(QtCore.QSize(0, 0))
        Settings.setMaximumSize(QtCore.QSize(1000, 1000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Pictures/Logos/klinklinom-1000pxv5-1024x1024.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Settings.setWindowIcon(icon)
        Settings.setStyleSheet("font: 75 10pt \"Comfortaa\";\n"
"background: #3a3a3a;")
        self.layoutWidget = QtWidgets.QWidget(Settings)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 621, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.main_Link = QtWidgets.QGridLayout(self.layoutWidget)
        self.main_Link.setContentsMargins(0, 0, 0, 0)
        self.main_Link.setObjectName("main_Link")
        self.label_link_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_link_2.setFont(font)
        self.label_link_2.setStyleSheet("color: #fff;\n"
"margin-right: 20px;")
        self.label_link_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_link_2.setObjectName("label_link_2")
        self.main_Link.addWidget(self.label_link_2, 1, 0, 1, 1)
        self.lineEdit_UserName = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_UserName.setStyleSheet("background: #fff;\n"
"color: #000;\n"
"padding: 10px;\n"
"border-radius: 20px;")
        self.lineEdit_UserName.setText("")
        self.lineEdit_UserName.setObjectName("lineEdit_UserName")
        self.main_Link.addWidget(self.lineEdit_UserName, 0, 2, 1, 1)
        self.label_link = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_link.setFont(font)
        self.label_link.setStyleSheet("color: #fff;\n"
"margin-right: 20px;")
        self.label_link.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_link.setObjectName("label_link")
        self.main_Link.addWidget(self.label_link, 0, 0, 1, 1)
        self.lineEdit_UserLink = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_UserLink.setStyleSheet("background: #fff;\n"
"color: #000;\n"
"padding: 10px;\n"
"border-radius: 20px;")
        self.lineEdit_UserLink.setInputMask("")
        self.lineEdit_UserLink.setText("")
        self.lineEdit_UserLink.setObjectName("lineEdit_UserLink")
        self.main_Link.addWidget(self.lineEdit_UserLink, 1, 2, 1, 1)
        self.label_link_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_link_3.setFont(font)
        self.label_link_3.setStyleSheet("color: #fff;\n"
"margin-right: 20px;")
        self.label_link_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_link_3.setObjectName("label_link_3")
        self.main_Link.addWidget(self.label_link_3, 2, 0, 1, 1)
        self.lineEdit_UserImage = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_UserImage.setStyleSheet("background: #fff;\n"
"color: #000;\n"
"padding: 10px;\n"
"border-radius: 20px;")
        self.lineEdit_UserImage.setText("")
        self.lineEdit_UserImage.setObjectName("lineEdit_UserImage")
        self.main_Link.addWidget(self.lineEdit_UserImage, 2, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Settings)
        self.pushButton.setGeometry(QtCore.QRect(20, 320, 121, 41))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background: #a016f0;\n"
"color: #fff;\n"
"border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_Cancel = QtWidgets.QPushButton(Settings)
        self.pushButton_Cancel.setGeometry(QtCore.QRect(150, 320, 121, 41))
        self.pushButton_Cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Cancel.setStyleSheet("background: #a016f0;\n"
"color: #fff;\n"
"border-radius: 10px;")
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.layoutWidget_2 = QtWidgets.QWidget(Settings)
        self.layoutWidget_2.setGeometry(QtCore.QRect(450, 290, 191, 72))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.other_Input = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.other_Input.setContentsMargins(0, 0, 0, 0)
        self.other_Input.setObjectName("other_Input")
        self.lineEdit_color = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_color.setStyleSheet("background: #fff;\n"
"color: #000;\n"
"padding: 10px;\n"
"border-radius: 20px;")
        self.lineEdit_color.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_color.setInputMask("")
        self.lineEdit_color.setText("")
        self.lineEdit_color.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_color.setObjectName("lineEdit_color")
        self.other_Input.addWidget(self.lineEdit_color, 2, 2, 1, 1)
        self.label_color = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_color.setFont(font)
        self.label_color.setStyleSheet("color: #fff;")
        self.label_color.setAlignment(QtCore.Qt.AlignCenter)
        self.label_color.setObjectName("label_color")
        self.other_Input.addWidget(self.label_color, 1, 2, 1, 1)
        self.lineEdit_UserWebhook = QtWidgets.QLineEdit(Settings)
        self.lineEdit_UserWebhook.setGeometry(QtCore.QRect(60, 230, 581, 43))
        self.lineEdit_UserWebhook.setStyleSheet("background: #fff;\n"
"color: #000;\n"
"padding: 10px;\n"
"border-radius: 20px;")
        self.lineEdit_UserWebhook.setText("")
        self.lineEdit_UserWebhook.setObjectName("lineEdit_UserWebhook")
        self.label_link_4 = QtWidgets.QLabel(Settings)
        self.label_link_4.setGeometry(QtCore.QRect(20, 180, 175, 43))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_link_4.setFont(font)
        self.label_link_4.setStyleSheet("color: #fff;")
        self.label_link_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_link_4.setObjectName("label_link_4")

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Настройки | Kuнoмaнuя NEWS"))
        self.label_link_2.setWhatsThis(_translate("Settings", "<html><head/><body><p><br/></p></body></html>"))
        self.label_link_2.setText(_translate("Settings", "Ссылка на страницу"))
        self.lineEdit_UserName.setPlaceholderText(_translate("Settings", "Иван иванович"))
        self.label_link.setWhatsThis(_translate("Settings", "<html><head/><body><p><br/></p></body></html>"))
        self.label_link.setText(_translate("Settings", "Имя пользователя"))
        self.lineEdit_UserLink.setPlaceholderText(_translate("Settings", "https://vk.com/havename"))
        self.label_link_3.setWhatsThis(_translate("Settings", "<html><head/><body><p><br/></p></body></html>"))
        self.label_link_3.setText(_translate("Settings", "Ссылка на картинку"))
        self.lineEdit_UserImage.setPlaceholderText(_translate("Settings", "https://"))
        self.pushButton.setText(_translate("Settings", "Сохранить"))
        self.pushButton_Cancel.setText(_translate("Settings", "Отмена"))
        self.label_color.setText(_translate("Settings", "Цвет"))
        self.lineEdit_UserWebhook.setPlaceholderText(_translate("Settings", "https://discord.com/api/webhooks"))
        self.label_link_4.setWhatsThis(_translate("Settings", "<html><head/><body><p><br/></p></body></html>"))
        self.label_link_4.setText(_translate("Settings", "Discord Webhook"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings = QtWidgets.QDialog()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())
